version: '3'

services:

  scheduler:
    image: ghcr.io/dask/dask:latest
    hostname: scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    networks:
      - etl-net
    command: ["dask-scheduler"]

  worker:
    image: ghcr.io/dask/dask:latest
    command: ["dask-worker", "tcp://scheduler:8786"]
    depends_on:
      - scheduler
    networks:
      - etl-net
    deploy:
      replicas: 4

  controller:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && python -u controller.py"
    depends_on:
      - scheduler
    networks:
      - etl-net




networks:
  etl-net:
    driver: bridge


